# https://zgadzaj.com/development/docker/docker-compose/containers/mongodb
# https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    ports:
        - 27017:27017
    volumes:
        - ~/.docker/data/mongo/:/data/db/
